name: C++ package

on: [push, pull_request]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Debug

jobs:
  build-cpp:
    name: "Build and test: C++ ${{ matrix.config.name}}"
    runs-on: ${{ matrix.config.os }}
    strategy:
      max-parallel: 4
      matrix:
        config:
          - { name: "Ubuntu gcc", os: ubuntu-latest, cc: "gcc", cxx: "g++" }
    steps:
      - uses: actions/checkout@v2
      - name: Cache
        if: ${{ !env.ACT }} # Cache not working due to https://github.com/nektos/act/issues/329
        uses: actions/cache@master
        env:
          # Increase this value to reset cache if environment.yaml has not changed
          CACHE_NUMBER: 0
        with:
          path: ~/cpp_pkgs_dir
          key: ${{ runner.os }}-python${{ matrix.python-version }}-${{ env.CACHE_NUMBER }} }}
      - name: Install Python
        uses: actions/setup-python@v2
      - name: Setup cmake
        uses: jwlawson/actions-setup-cmake@v1.9
        with:
          cmake-version: "3.20.x"
      - name: (Ubuntu) Install G++ and libtorch
        if: ${{ matrix.config.os == 'ubuntu-latest' }}
        run: |
          sudo apt update
          sudo apt install g++ libgtest-dev ninja-build -y
          wget https://download.pytorch.org/libtorch/cpu/libtorch-shared-with-deps-1.9.0%2Bcpu.zip -O ${{ github.workspace }}/libtorch.zip
          unzip -q ${{ github.workspace }}/libtorch.zip -d ${{ github.workspace }}/
      - name: Build
        env:
          CC: ${{ matrix.config.cc }}
          CXX: ${{ matrix.config.cxx }}
        run: |
          cmake -GNinja -B build -S . -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }} -DCMAKE_PREFIX_PATH=${{ github.workspace }}/libtorch
          cmake --build build
      - name: Test
        run: |
          ctest --test-dir build/norse/csrc
