name: Documentation Publish

on:
  push:
    branches:
      - master

jobs:
  publish-docs:
    runs-on: ubuntu-latest

    steps: 
      - uses: actions/checkout@v1
<<<<<<< HEAD
      - name: Setup C++
        run: sudo apt update && sudo apt install gcc-10 g++-10
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v1
=======
      - name: Set up Python
        uses: actions/setup-python@v2
>>>>>>> c914eda... Improved doc building
        with:
          python-version: '3.x'
      - name: Compile docs
        uses: ammaraskar/sphinx-action@master
        with:
          docs-folder: "docs/"
          pre-build-command: |
            python -m pip install --upgrade pip
            pip install -r requirements-dev.txt
            pip install -e .
            sphinx-apidoc -o docs/source/auto_api -H Norse -f -e -M norse/
      - name: Commit documentation changes
        run: |
          git clone https://github.com/norse/norse --branch gh-pages --single-branch gh-pages
          cp -r docs/build/html/* gh-pages/
          cd gh-pages
          git config --local user.email "docbot@norse.ai"
          git config --local user.name "docbot"
          git add .
          git commit -m "Update documentation" -a || true
          # The above command will fail if no changes were present, so we ignore
          # the return code.
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          branch: gh-pages
          directory: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
