name: Build via Spack

on:
  pull_request:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: [3.9]
        compiler-version: [gcc@11.3.0]
        spack-python: ['python@3.7', 'python@3.10']
        spack-pytorch: ['py-torch@1.9', 'py-torch@1.11']
        exclude:
          # dep. py-torchvision for py-torch@1.9 is limited to python@3.6:3.9
          - spack-python: 'python@3.10'
            spack-pytorch: 'py-torch@1.9'
    steps:
      - uses: actions/checkout@master
      - name: Spack cache
        uses: actions/cache@v2
        with:
          path: ~/.spack-cache
          key: cache-spack-${{ github.ref }}-${{ matrix.os }}-${{ matrix.python-version }}-${{ matrix.spack-python }}-${{ matrix.spack-pytorch }}
          restore-keys: |
            cache-spack-main-latest-${{ matrix.os }}-${{ matrix.python-version }}-${{ matrix.spack-python }}-${{ matrix.spack-pytorch }}
            cache-spack-main-latest
      - name: Build norse's Spack package
        env:
          MATRIX_SPACK_PYTHON: ${{ matrix.spack-python }}
          MATRIX_SPACK_PYTORCH: ${{ matrix.spack-pytorch }}
          COMPILER_VERSION: ${{ matrix.compiler-version }}
        run: .github/spack/build_spack_package.sh
